// This file is generated by Sim IDX. Do not edit manually.
import { pgEnum, pgTable as table } from "drizzle-orm/pg-core";
import * as t from "drizzle-orm/pg-core";
import { db, types } from "@duneanalytics/sim-idx";

export const borrow = table("borrow", {
  txnHash: db.bytes32('txn_hash'),
  chainId: db.uint64('chain_id'),
  blockNumber: db.uint64('block_number'),
  blockTimestamp: db.uint64('block_timestamp'),
  reserve: db.address('reserve'),
  user: db.address('user'),
  onBehalfOf: db.address('on_behalf_of'),
  amount: db.uint256('amount'),
  interestRateMode: db.uint8('interest_rate_mode'),
  borrowRate: db.uint256('borrow_rate'),
  referralCode: db.uint16('referral_code'),
  totalSupply: db.uint256('total_supply'),
})
